### ISSUE TITLE
Alternative way for poetry

### ISSUE THREAD

**Issue by yuhangjiang22** [JohnGiorgi/seq2rel#369]
I have trouble installing poetry on our school's clusters, is there an alternative way to run the code? (e.g. directly run a .py file)

**Comment by JohnGiorgi** [comment]
Do the instructions in the [README](https://github.com/JohnGiorgi/seq2rel#installing-the-library-and-dependencies) for installing straight from GitHub not work?

```bash
pip install git+https://github.com/JohnGiorgi/seq2rel.git
```

**Comment by yuhangjiang22** [comment]
I'm not quite sure what installing straight from GitHub does. Because I do want to modify the code, would this help it?

**Comment by JohnGiorgi** [comment]
I see. I can think of two options

## Option 1

Create a wheel on your local computer, move it to the cluster, and pip install that. The procedure would look roughly as follows:

On your local computer...

```bash
# Install poetry for your system: https://python-poetry.org/docs/#installation
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

# Clone and move into the repo
git clone https://github.com/JohnGiorgi/seq2rel
cd seq2rel

# Install the package with poetry
poetry build
```

Then, move the wheel to the cluster and install with pip inside a virtual env

```bash
# Activate your env, then
pip install -e <path_to_wheel>
```

If you know where pip is installing packages, you could edit the source from there?

## Option 2

Create a requirments.txt file on your local computer, move it to the cluster, and pip install that. The procedure would look roughly as follows:

On your local computer...

```
# Install poetry for your system: https://python-poetry.org/docs/#installation
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

# Clone and move into the repo
git clone https://github.com/JohnGiorgi/seq2rel
cd seq2rel

# Install the package with poetry
poetry export -f requirements.txt --output requirements.txt --without-hashes
```

Then, move the requirements.txt file to the cluster and install with pip inside a virtual env

```bash
# Activate your env, then

# Clone and move into the repo
git clone https://github.com/JohnGiorgi/seq2rel
cd seq2rel
pip install -r requirements.txt
```

This is just installing the dependencies and not the package itself, so I am not sure if you will run into issues

**Comment by yuhangjiang22** [comment]
For the option 1, I've run the 
`pip install -e <path_to_wheel>` 
and got the following:
`seq2rel-0.1.0-py3-none-any.whl is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).`



For the option 2, I've run the allennlp command and got the following:
`local/bin/allennlp: /opt/conda/bin/python3.8: bad interpreter: No such file or directory`

Not sure how should I fix this.

**Comment by JohnGiorgi** [comment]
Sorry, I will need more info to help you in either case. Is `path_to_wheel` the correct path to the wheel you built? What if you try installing without editable mode (remove the `-e` argument)? What allennlp command?

**Comment by yuhangjiang22** [comment]
I've tried to remove `-e` argument, it worked.

But when I was trying to run 
`train_data_path="cdr/train.tsv" \
valid_data_path="cdr/valid.tsv" \
dataset_size=500 \
allennlp train "training_config/cdr.jsonnet" \
--serialization-dir "output" \
--include-package "seq2rel" `

I still got 
`local/bin/allennlp: /opt/conda/bin/python3.8: bad interpreter: No such file or directory`

**Comment by JohnGiorgi** [comment]
This looks like a problem with your python environment. Can you confirm you can run non-seq2rel related python 
code? E.g. what happens when you call `python` or `which python` at the command line with your virtual environment activated?

**Comment by yuhangjiang22** [comment]
I can directly call a test.py file
`python test.py`

When I open .local/bin/allennlp on the clusters, I found the following

> #!/opt/conda/bin/python3.8
> # -*- coding: utf-8 -*-
> import re
> import sys
> from allennlp.__main__ import run
> if __name__ == '__main__':
>     sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
>     sys.exit(run())

Should I change the first line to something else?

**Comment by JohnGiorgi** [comment]
Hmm, I am not sure how your school's clusters are set up or what the purpose of the `.local/bin/allennlp` file is. I am also a little unsure how your python environment is setup (e.g. is it a conda env that you have installed seq2rel and all its dependencies into?), so I am not sure how to help

**Comment by yuhangjiang22** [comment]
Okay, I appreciate your help!
