### ISSUE TITLE
Demo Link not working

### ISSUE THREAD

**Issue by REEMALIK94** [JohnGiorgi/seq2rel#384]
Hey,

I am trying to open the Demo, but it's not working. Can you please help, need to go through it for my college project.

Thanks
Reewa

**Comment by JohnGiorgi** [comment]
Unfortunately, the demo is super fragile, as Streamlits' free resource limits are barely enough to run the model. I just rebooted it now; it should work for a bit but will probably go down again. You could try running it locally though? You just need to `pip install` some extra dependencies:

https://github.com/JohnGiorgi/seq2rel/blob/f757d6cc9da87ac527a9485d54843b6a5739657f/pyproject.toml#L58-L60

and then `streamlit run demo.py`. I added the same instructions to the readme in #385.

**Comment by JohnGiorgi** [comment]
I also emailed streamlit support and asked them to increase the resource limit, so I will update you if that is granted!

**Comment by JohnGiorgi** [comment]
Okay streamlit bumped the apps resources limits so the demo should stay online! Closing.

**Comment by REEMALIK94** [comment]
Thanks a lot!, its working.
