### ISSUE TITLE
seq2rel

### ISSUE THREAD

**Issue by wucui5** [JohnGiorgi/seq2rel#389]

**Comment by wucui5** [comment]
Hi, When I used the CDR configuration to make a call to "allennlp train", an error occurred indicating that the "seq2rel" module could not be found. I copied the path for the "seq2rel" module directly, what could be the issue?
![image](https://github.com/JohnGiorgi/seq2rel/assets/131764970/08600c1c-2af6-4670-a25f-949cb9ad74e0)

![image](https://github.com/JohnGiorgi/seq2rel/assets/131764970/5363cae3-19df-4c55-aee6-6d88333f03a1)

**Comment by JohnGiorgi** [comment]
Going to close this as its empty, but lmk if there's something I can help with.
